---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: secret-checker
webhooks:
  - name: demo.avolens.net
    failurePolicy: Ignore
    timeoutSeconds: 1
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["secrets"]
    clientConfig:
      url: https://demo.avolens.net/
